version: '3.8'

services:
  web:
    build: .
    container_name: nextjs_app
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    restart: always